# Generated by Django 5.2.6 on 2025-09-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('publications_count', models.PositiveIntegerField(default=0)),
                ('projects_supervised', models.PositiveIntegerField(default=0)),
                ('is_active_faculty', models.BooleanField(default=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
